branches:
  - name: main
    channel: latest
  - name: pre-release
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git":
      assets:
        - "CHANGELOG.md"
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github":
      assets:
        - path: "**/*"
          label: "Theme files"    
preset: "conventionalcommits"
ci: false
dryRun: false
debug: true