name: Semantic Release

on:
  push:
    branches:
      - main
      - pre-release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        pull-requests: write
        id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm ci

      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
          DEBUG: "semantic-release:*"
